# Generated by Django 4.2.7 on 2026-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_register_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
