# Generated by Django 4.2.7 on 2026-02-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_register_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
