# Generated by Django 4.2.7 on 2026-02-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_register_is_verified_register_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='otp_expiry',
        ),
    ]
