# Generated by Django 4.2.7 on 2026-02-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_first_name_register_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='register',
            name='otp',
        ),
    ]
