# Generated by Django 4.2.7 on 2026-02-07 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_remove_register_is_verified_remove_register_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsteroidCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asteroid_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
                ('estimated_diameter_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estimated_diameter_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close_approach_date', models.DateField()),
                ('miss_distance_km', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hazardous_filter', models.BooleanField(default=False)),
                ('default_min_size', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_max_proximity', models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('items_per_page', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedAsteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asteroid_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('notification_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in LD (Lunar Distance) for notifications', max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_asteroids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
                'unique_together': {('user', 'asteroid_id')},
            },
        ),
    ]
