# Generated by Django 4.2.7 on 2026-02-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_dashboardpreference_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsteroidCache',
        ),
        migrations.AlterUniqueTogether(
            name='watchedasteroid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchedasteroid',
            name='user',
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='DashboardPreference',
        ),
        migrations.DeleteModel(
            name='WatchedAsteroid',
        ),
    ]
