# Generated by Django 4.2.7 on 2026-02-08 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_asteroidcache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='app1.register')),
                ('avatar_url', models.URLField(blank=True, default=None, help_text="URL to user's profile picture", max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography about the user', max_length=500)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('profession', models.CharField(blank=True, help_text="User's profession/occupation", max_length=100, null=True)),
                ('organization', models.CharField(blank=True, help_text='Company/Organization', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Personal website or portfolio', null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter username', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('auto', 'Auto (System)')], default='light', help_text='UI theme preference', max_length=20)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('profile_views', models.PositiveIntegerField(default=0, help_text='Number of times profile was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_profile_update', models.DateTimeField(blank=True, help_text='Last time profile was updated', null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app1.register')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert'), ('success', 'Success'), ('asteroid', 'Asteroid Update'), ('system', 'System Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='URL to take action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiration date', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.register')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='app1.register')),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_view', 'Profile Viewed'), ('profile_update', 'Profile Updated'), ('dashboard_access', 'Dashboard Accessed'), ('asteroid_view', 'Asteroid Data Viewed'), ('analytics_view', 'Analytics Viewed'), ('password_change', 'Password Changed'), ('account_delete', 'Account Deletion Requested')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional activity details', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app1.register')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='app1_userac_user_id_08e4b8_idx'), models.Index(fields=['activity_type', 'timestamp'], name='app1_userac_activit_f70a66_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteAsteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asteroid_id', models.CharField(help_text='NASA asteroid ID', max_length=20)),
                ('asteroid_name', models.CharField(help_text='Name of the asteroid', max_length=100)),
                ('notes', models.TextField(blank=True, help_text="User's notes about this asteroid", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_asteroids', to='app1.register')),
            ],
            options={
                'verbose_name': 'Favorite Asteroid',
                'verbose_name_plural': 'Favorite Asteroids',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'asteroid_id')},
            },
        ),
    ]
