# Generated by Django 4.2.7 on 2026-02-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_userprofile_alter_register_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_login',
        ),
        migrations.DeleteModel(
            name='FavoriteAsteroid',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
